# Site Specific Configuration
name: tomjack.ca
description: Thomas' Personal Site
url: https://tomjack.ca
author: tajacks
timezone: America/Toronto
timezone_short: ET

# Styling
sass:
  sass_dir: _sass
  style: expanded # compressed, compact, expanded or compressed

#seo
keywords: ['java', 'coffee', 'elixir', 'functional', 'programming']

# Paginate
pagination:
  enabled: true
  per_page: 10
  indexpage: 'index'
  sort_field: 'date'
  sort_reverse: true

# Category Paginating
autopages:
  enabled: true
  categories:
    title: 'Posts in category :cat'
    permalink: '/category/:cat'
    silent: false

# Exclusions
exclude: [ 'README.md', 'COPYING', 'drafts', 'templates' ]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag